[tool.black]
line-length = 79

[tool.pytest.ini_options]
filterwarnings = [
    # TO REMOVE IN 2024
    # kinematics
    'ignore:The function read_c3d_file is deprecated since 0.9 and is scheduled to be removed in 2024:FutureWarning',    
    'ignore:The function read_n3d_file is deprecated since 0.9 and is scheduled to be removed in 2024:FutureWarning',    

    # TimeSeries
    'ignore:The function get_ts_at_event is deprecated since 0.10.0 and is scheduled to be removed in 2024:FutureWarning',
    'ignore:The function get_event_time is deprecated since 0.10.0 and is scheduled to be removed in 2024:FutureWarning',
    
    # Player
    'ignore:The function to_html5 is deprecated since 0.12 and is scheduled to be removed in 2024:FutureWarning',

]
